name = "FluidSuperResolution"
uuid = "ca4fd82c-9edb-4331-9f15-2c3767ecc99d"
authors = ["Paul Matlashewski <pmatlashewski@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
